package com.example.shop49k.model.userInfo

data class UserInfoData (

	val id : Int,
	val oauth_uid : String,
	val oauth_provider : String,
	val ip_address : String,
	val job : String,
	val username : String,
	val avatar : String,
	val gender : Int,
	val email : String,
	val forgotten_password_time : Int,
	val created_on : String,
	val last_login : String,
	val active : Int,
	val fullname : String,
	val first_name : String,
	val last_name : String,
	val address_book : String,
	val company : String,
	val phone : String,
	val dob : String,
	val created_time : String,
	val updated_time : String,
	val identity_number : String,
	val shop_name : String,
	val merchant_id : String,
	val city_id : String,
	val district_id : String,
	val commune_id : String,
	val business_area : String,
	val address : String,
	val fontside_image_identity_cart : String,
	val backside_image_identity_cart : String,
	val description : String,
	val shop_created : String,
	val shop_address : String,
	val merchant_short_code : String,
	val user_images : List<User_images>,
	val city_data : City_data,
	val district_data : District_data,
	val commune_data : Commune_data,
	val offer_count : Int,
	val merchant_registration_front_site : String,
	val merchant_registration_back_site : String,
	val bank_account_number : String,
	val bank_id : String,
	val shop_city_id : String,
	val shop_district_id : String,
	val shop_commune_id : String,
	val group_id:String
)